In [2]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [5]:
#Provide data to work with. The inputs (regressors, 𝑥) and output (predictor, 𝑦)
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])
print(x)

[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]]


In [6]:
#Create a linear regression model and fit it using the existing data.
model = LinearRegression()

In [7]:
#Using the model, first, we need to call .fit() on model
model.fit(x, y)

LinearRegression()

In [8]:
#Simple way of writing the above two statements is
model = LinearRegression().fit(x, y)

In [10]:
#Once we have your model fitted, we can get the results to check whether the model
#works satisfactorily and interpret it.we can obtain the coefficient of determination
#(𝑅²) with .score() called on model
r_sq = model.score(x, y)
print('coefficient of determination:', r_sq)

coefficient of determination: 0.715875613747954


In [12]:
#The attributes of model are .intercept_, which represents the coefficient, 𝑏₀ and coef_,
#which represents 𝑏₁:
print('intercept:', model.intercept_)
print('slope:', model.coef_)

intercept: 5.633333333333329
slope: [0.54]


In [13]:
#Predict response once there is a satisfactory model, you can use it for predictions with
#either existing or new data.To obtain the predicted response, use .predict():
y_pred = model.predict(x)
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [14]:
#An identical way to predict the response:
y_pred = model.intercept_ + model.coef_ * x
print('predicted response:', y_pred, sep='\n')

predicted response:
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]
